# Generated by Django 4.2.13 on 2024-05-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0004_attachmentgroup_attachment_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="groups",
            field=models.ManyToManyField(blank=True, to="ems.attachmentgroup"),
        ),
    ]
