# Generated by Django 4.2.13 on 2024-06-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0005_alter_attachment_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyReadingTariffRegister",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="energyreading",
            name="tariff_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems.energyreadingtariffregister",
            ),
        ),
    ]
