# Generated by Django 4.2.13 on 2024-06-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0006_energyreadingtariffregister_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyReadingComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "energy_reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems.energyreading",
                    ),
                ),
            ],
        ),
    ]
