# Generated by Django 4.2.14 on 2024-09-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0007_energyreadingcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel xlsx"),
                            ("json", "JSON"),
                        ],
                        max_length=255,
                    ),
                ),
                ("periode_from", models.DateTimeField()),
                ("periode_to", models.DateTimeField()),
                (
                    "target_timezone",
                    models.CharField(
                        choices=[("UTC", "UTC"), ("CET", "CET")], max_length=255
                    ),
                ),
                (
                    "include_cost",
                    models.BooleanField(help_text="add a column with the energy cost"),
                ),
                (
                    "include_coverage",
                    models.BooleanField(
                        help_text=(
                            "add a column with the data coverage of"
                            " virtual metering points"
                        )
                    ),
                ),
                (
                    "export_file_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="name of the Export File without file extension",
                        max_length=255,
                    ),
                ),
                (
                    "attribute_keys",
                    models.ManyToManyField(blank=True, to="ems.attributekey"),
                ),
                (
                    "interval_length",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems.calculatedmeteringpointenergydeltainterval",
                    ),
                ),
                (
                    "metering_points",
                    models.ManyToManyField(blank=True, to="ems.meteringpoint"),
                ),
                (
                    "virtual_metering_points",
                    models.ManyToManyField(blank=True, to="ems.virtualmeteringpoint"),
                ),
            ],
        ),
    ]
